[build-system]
requires = [
    'django_evolution~=2.3',
    'setuptools>=74',
]
build-backend = 'build-backend'
backend-path = ['.']

[project]
name = 'Djblets'
description = 'A collection of useful classes and functions for developing large-scale Django-based web applications.'
authors = [
    {name = 'Beanbag, Inc.', email = 'questions@beanbaginc.com'},
]
license = { text = 'MIT' }
readme = 'README.rst'
requires-python = '>=3.8'
dynamic = ['dependencies', 'version']

classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Django :: 4.2',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Topic :: Software Development',
    'Topic :: Software Development :: Libraries :: Python Modules',
]


[project.urls]
Homepage = 'https://github.com/djblets/djblets'
Documentation = 'https://github.com/djblets/djblets'
Repository = 'https://github.com/djblets/djblets'
Support = 'https://www.reviewboard.org/support/'



[tool.basedpyright]
enableTypeIgnoreComments = true
pythonVersion = "3.8"
reportAny = "none"
reportCallInDefaultInitializer = "none"
reportConstantRedefinition = "none"
reportExplicitAny = "none"
reportIgnoreCommentWithoutRule = "none"
reportImplicitOverride = "none"
reportImplicitStringConcatenation = "none"
reportImportCycles = "none"
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportMissingParameterType = "none"
reportMissingSuperCall = "none"
reportMissingTypeStubs = "none"
reportPrivateUsage = "none"
reportUnannotatedClassAttribute = "none"
reportUninitializedInstanceVariable = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnnecessaryIsInstance = "none"
reportUnsafeMultipleInheritance = "none"
reportUnusedCallResult = "none"
reportUnusedParameter = "none"

[tool.isort]
combine_as_imports = true
include_trailing_comma = true
lines_after_imports = 2
multi_line_output = 3

[tool.ruff]
line-length = 79
preview = true
target-version = "py38"

[tool.ruff.lint]
extend-select = ["ANN", "COM", "C4", "D", "DJ", "DTZ", "E", "F", "FA", "G", "INT", "LOG", "N", "PIE", "PL", "PT", "Q", "RET", "RUF", "SIM", "TC", "UP", "W"]
ignore = ["ANN002", "ANN003", "ANN401", "COM812", "D200", "D203", "D205", "D213", "D301", "D400", "D405", "D406", "D407", "D413", "D415", "DJ001", "DJ007", "DJ012", "N812", "PIE790", "PLC0415", "PLC1901", "PLR09", "PLR1702", "PLR2004", "PLR5501", "PLR6301", "PLW0603", "PLW2901", "PT009", "PT027", "RET505", "RET506", "RET507", "RET508", "RUF012", "RUF031", "SIM105", "SIM108", "TC006", "UP012", "UP013", "UP015"]

[tool.ruff.lint.per-file-ignores]
"djblets/features/testing.py" = ["N801"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"


[tool.ruff.lint.pep8-naming]
extend-ignore-names = ["assertQueries", "shortDescription"]


[tool.ruff.lint.pycodestyle]
max-line-length = 79


[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.ruff.lint.ruff]
parenthesize-tuple-in-subscript = true

[tool.setuptools.package-data]
djblets = ['py.typed']


[tool.setuptools.packages.find]
where = ['.']
include = ['djblets*']
namespaces = false


[tool.setuptools.dynamic]
dependencies = { file = 'package-requirements.txt' }
version = { attr = 'djblets.__version__' }
