[tox]
envlist =
	py{310,311,312,313,314}

skipsdist = True

[testenv]
commands = pytest {posargs}
usedevelop = True
install_command = python -I -m pip install --no-build-isolation {opts} {packages}

deps =
	-r dev-requirements.txt

passenv = *
setenv =
    PYTHONPATH = {toxinidir}
