[tox]
envlist =
	py{310,311,312,313,314}

[testenv]
commands = pytest {posargs}
package = editable
install_command = python -I -m pip install {opts} {packages}

deps =
	-r dev-requirements.txt

passenv = *
setenv =
    PYTHONPATH = {toxinidir}
